CREATE TABLE [dbo].[TBTurma] (
    [Id]                UNIQUEIDENTIFIER NOT NULL,
    [CURSO_ID]          UNIQUEIDENTIFIER NOT NULL,
    [INSTRUTOR_ID]      UNIQUEIDENTIFIER NOT NULL,
    [NOME]              NVARCHAR (100)   NOT NULL,
    [DATA_INICIO]       DATE             NOT NULL,
    [DATA_TERMINO]      DATE             NOT NULL,
    [CAPACIDADE_ALUNOS] INT              NOT NULL
);
GO

CREATE NONCLUSTERED INDEX [IX_TBTurma_INSTRUTOR_ID]
    ON [dbo].[TBTurma]([INSTRUTOR_ID] ASC);
GO

CREATE NONCLUSTERED INDEX [IX_TBTurma_CURSO_ID]
    ON [dbo].[TBTurma]([CURSO_ID] ASC);
GO

ALTER TABLE [dbo].[TBTurma]
    ADD CONSTRAINT [FK_TBTurma_TBInstrutor_INSTRUTOR_ID] FOREIGN KEY ([INSTRUTOR_ID]) REFERENCES [dbo].[TBInstrutor] ([Id]);
GO

ALTER TABLE [dbo].[TBTurma]
    ADD CONSTRAINT [FK_TBTurma_Curso_CURSO_ID] FOREIGN KEY ([CURSO_ID]) REFERENCES [dbo].[Curso] ([Id]);
GO

ALTER TABLE [dbo].[TBTurma]
    ADD CONSTRAINT [PK_TBTurma] PRIMARY KEY CLUSTERED ([Id] ASC);
GO

